version: "3"
services:
  db:
    build: ./pkg/controller/store/mysql
    command:
      - --performance_schema=0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=deviceplane
    ports:
      - "3313:3306"
